In [1]:
# Data Science Course Week 1 - Data Manipulation using Pandas

## Here we will be using real data sources to explore the features of Pandas


In [2]:
import pandas as pd

In [6]:
1==5

False

# Class Workshop

## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [9]:
import numpy as np

### Creating ndarrays
An array object represents a multidimensional, homogeneous array of fixed-size items.

In [12]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a,b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [17]:
help(np.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

In [20]:

c = a-b
a,b,c

(array([20, 30, 40, 50]), array([0, 1, 2, 3]), array([20, 29, 38, 47]))

In [8]:
b**2

array([0, 1, 4, 9])

In [21]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
help(np.random.randint)

Help on built-in function randint:

randint(...)
    randint(low, high=None, size=None)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution in the
    "half-open" interval [`low`, `high`). If `high` is None (the default),
    then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is the *highest* such
        integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    

In [10]:
a

array([ 0.,  0.,  0.])

In [11]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
c

array([[[1, 4, 2, 7],
        [3, 2, 8, 4],
        [4, 1, 9, 4]],

       [[8, 5, 7, 3],
        [7, 8, 3, 9],
        [7, 6, 2, 6]]])

## Indexing, Slicing and Iterating

In [22]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [23]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [24]:
a[2:5]

array([ 4,  9, 16])

In [25]:
a[0:3]

array([0, 1, 4])

In [26]:
a[1:3]

array([1, 4])

### Reading Files, Selecting Columns, and Summarizing

MovieLens 100k movie rating data:
    main page: http://grouplens.org/datasets/movielens/
    data dictionary: http://files.grouplens.org/datasets/movielens/ml-100k-README.txt
    files: u.user, u.data, u.item

In [27]:
# can read a file from local computer or directly from a URL
pd.read_table('u.user', header=None)

0
0         1|24|M|technician|85711
1              2|53|F|other|94043
2             3|23|M|writer|32067
3         4|24|M|technician|43537
4              5|33|F|other|15213
5          6|42|M|executive|98101
6      7|57|M|administrator|91344
7      8|36|M|administrator|05201
8            9|29|M|student|01002
9            10|53|M|lawyer|90703
10            11|39|F|other|30329
11            12|28|F|other|06405
12         13|47|M|educator|29206
13        14|45|M|scientist|55106
14         15|49|F|educator|97301
15    16|21|M|entertainment|10309
16       17|30|M|programmer|06355
17            18|35|F|other|37212
18        19|40|M|librarian|02138
19        20|42|F|homemaker|95660
20           21|26|M|writer|30068
21           22|25|M|writer|40206
22           23|30|F|artist|48197
23           24|21|F|artist|94533
24         25|39|M|engineer|55107
25         26|49|M|engineer|21044
26        27|40|F|librarian|30030
27           28|32|M|writer|55369
28       29|41|M|programmer|94043
29           30|7|M|student|55436
..                            ...
913          914|44|F|other|08105
914  915|50|M|entertainment|60614
915       916|27|M|engineer|N2L5N
916        917|22|F|student|20006
917      918|40|M|scientist|70116
918          919|25|M|other|14216
919         920|30|F|artist|90008
920        921|20|F|student|98801
921  922|29|F|administrator|21114
922        923|21|M|student|E2E3R
923          924|29|M|other|11753
924       925|18|F|salesman|49036
925  926|49|M|entertainment|01701
926     927|23|M|programmer|55428
927        928|21|M|student|55408
928      929|44|M|scientist|53711
929      930|28|F|scientist|07310
930       931|60|M|educator|33556
931       932|58|M|educator|06437
932        933|28|M|student|48105
933       934|61|M|engineer|22902
934         935|42|M|doctor|66221
935          936|24|M|other|32789
936       937|48|M|educator|98072
937     938|38|F|technician|55038
938        939|26|F|student|33319
939  940|32|M|administrator|02215
940        941|20|M|student|97229
941      942|48|F|librarian|78209
942        943|22|M|student|77841

[943 rows x 1 columns]

Now having seen the data, read it in again but now with the pipe separator/delimiter.

In [28]:
# read 'u.user' and asign to 'users' so that we can re-use the data
user_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_table('u.user', sep='|', header=None, names=user_cols, index_col='user_id', dtype={'zip_code':str})

Now try running the example code below, uncommenting each line one at a time to see what results

In [35]:
# examine the users data

#users                   # print the first 30 and last 30 rows
#type(users)             # DataFrame
#users.head()            # print the first 5 rows
#users.head(10)          # print the first 10 rows
#users.tail()            # print the last 5 rows
#users.index             # "the index" (aka "the labels")
#users.columns           # column names (which is "an index")
#users.dtypes            # data types of each column
#users.shape             # number of rows and columns
#users.values            # underlying numpy array
users.info()            # concise summary (including memory usage)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 1 to 943
Data columns (total 4 columns):
age           943 non-null int64
gender        943 non-null object
occupation    943 non-null object
zip_code      943 non-null object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB


Now try some of the different methods for selecting a column from a dataframe by name.

In [23]:
# select a column

#users['gender']         # select one column
#type(users['gender'])   # Series
#users[['gender']]
#type(users[['gender']])   # DataFrame
#users.gender            # select one column using the DataFrame attribute


Now try some built in pandas methods for producing summary descriptive information from a dataframe.

In [43]:
# summarize (describe) the data

#users.describe()                    # describe all numeric columns
#users.describe(include=['object'])  # describe all object columns (can include multiple types)
users.describe(include='all')       # describe all columns
#users.age.describe()             # describe a single column
#users.age.mean()                    # only calculate the mean


age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [45]:
# count the number of occurrences of each value
users.occupation.value_counts()     # most useful for categorical variables
#users.age.value_counts()        # can also be used with numeric variables

student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
salesman          12
lawyer            12
none               9
homemaker          7
doctor             7
Name: occupation, dtype: int64

# Student Exercises

## Excercise One

### Data

WHO alcohol consumption data:
    article: http://fivethirtyeight.com/datalab/dear-mona-followup-where-do-people-drink-the-most-beer-wine-and-spirits/    
    original data: https://github.com/fivethirtyeight/data/tree/master/alcohol-consumption
    file: drinks.csv (with additional 'continent' column)


In [48]:
# read drinks.csv into a DataFrame called 'drinks'
drinks = pd.read_table('drinks.csv', sep=',')
#drinks = pd.read_csv('drinks.csv')              # assumes separator is comma

In [52]:
# print the head and the tail
#drinks.head()
#drinks.tail()
#drinks.describe()
drinks.country.describe()

count         193
unique        193
top       Lesotho
freq            1
Name: country, dtype: object

In [55]:
# examine the default index, data types, and shape
drinks.index
#drinks.dtypes
#drinks.shape

RangeIndex(start=0, stop=193, step=1)

In [57]:
# print the 'beer_servings' Series
drinks['beer_servings']
#drinks.beer_servings


0        0
1       89
2       25
3      245
4      217
5      102
6      193
7       21
8      261
9      279
10      21
11     122
12      42
13       0
14     143
15     142
16     295
17     263
18      34
19      23
20     167
21      76
22     173
23     245
24      31
25     231
26      25
27      88
28      37
29     144
      ... 
163    128
164     90
165    152
166    185
167      5
168      2
169     99
170    106
171      1
172     36
173     36
174    197
175     51
176     51
177     19
178      6
179     45
180    206
181     16
182    219
183     36
184    249
185    115
186     25
187     21
188    333
189    111
190      6
191     32
192     64
Name: beer_servings, dtype: int64

In [60]:
# calculate the average 'beer_servings' for the entire dataset
drinks.describe()                   # summarize all numeric columns
#drinks.beer_servings.describe()     # summarize only the 'beer_servings' Series
#drinks.beer_servings.mean()         # only calculate the mean


beer_servings  spirit_servings  wine_servings  \
count     193.000000       193.000000     193.000000   
mean      106.160622        80.994819      49.450777   
std       101.143103        88.284312      79.697598   
min         0.000000         0.000000       0.000000   
25%        20.000000         4.000000       1.000000   
50%        76.000000        56.000000       8.000000   
75%       188.000000       128.000000      59.000000   
max       376.000000       438.000000     370.000000   

       total_litres_of_pure_alcohol  
count                    193.000000  
mean                       4.717098  
std                        3.773298  
min                        0.000000  
25%                        1.300000  
50%                        4.200000  
75%                        7.200000  
max                       14.400000

In [63]:

# count the number of occurrences of each 'continent' value and see if it looks correct
drinks.continent.value_counts()
#drinks.country.value_counts()


AF    53
EU    45
AS    44
OC    16
SA    12
Name: continent, dtype: int64

#### Filtering and Sorting

using users data set again

In [69]:
# logical filtering: only show users with age < 20
#young_bool = users.age < 20         # create a Series of booleans...
#users[young_bool]                   # ...and use that Series to filter rows
#users[users.age < 20]               # or, combine into a single step
#users[users.age < 20].occupation    # select one column from the filtered results
users[users.age < 20].occupation.value_counts()     # value_counts of resulting Series

student          64
other             4
none              3
writer            2
entertainment     2
salesman          1
artist            1
Name: occupation, dtype: int64

In [74]:
# logical filtering with multiple conditions
users[(users.age  >= 20) & (users.gender=='M')]       # ampersand for AND condition
#users[(users.age < 20) | (users.age > 60)]          # pipe for OR condition
#users[users.occupation.isin(['doctor', 'lawyer'])]  # alternative to multiple OR conditions


age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
3         23      M         writer    32067
4         24      M     technician    43537
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
13        47      M       educator    29206
14        45      M      scientist    55106
16        21      M  entertainment    10309
17        30      M     programmer    06355
19        40      M      librarian    02138
21        26      M         writer    30068
22        25      M         writer    40206
25        39      M       engineer    55107
26        49      M       engineer    21044
28        32      M         writer    55369
29        41      M     programmer    94043
31        24      M         artist    10003
33        23      M        student    27510
37        23      M        student    55105
39        41      M  entertainment    01040
40        38      M      scientist    27514
41        33      M       engineer    80525
42        30      M  administrator    17870
44        26      M     technician    46260
45        29      M     programmer    50233
47        53      M      marketing    07102
48        45      M  administrator    12550
...      ...    ...            ...      ...
898       23      M      homemaker    61755
899       32      M          other    55116
900       60      M        retired    18505
901       38      M      executive    L1V3W
903       28      M       educator    20850
905       27      M          other    30350
906       45      M      librarian    70124
910       28      M     healthcare    29301
912       51      M          other    06512
913       27      M        student    76201
915       50      M  entertainment    60614
916       27      M       engineer    N2L5N
918       40      M      scientist    70116
919       25      M          other    14216
923       21      M        student    E2E3R
924       29      M          other    11753
926       49      M  entertainment    01701
927       23      M     programmer    55428
928       21      M        student    55408
929       44      M      scientist    53711
931       60      M       educator    33556
932       58      M       educator    06437
933       28      M        student    48105
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
940       32      M  administrator    02215
941       20      M        student    97229
943       22      M        student    77841

[625 rows x 4 columns]

In [77]:
# sorting
users.age.sort_values()                   # sort a column
#users.sort_values(by='age')                   # sort a DataFrame by a single column
#users.sort_values(by='age', ascending=False)  # use descending order instead
#users.sort_values(by=['occupation', 'age'])   # sort by multiple columns


user_id
30      7
471    10
289    11
880    13
609    13
142    13
674    13
628    13
813    14
206    14
887    14
849    15
281    15
461    15
618    15
179    15
101    15
57     16
580    16
550    16
451    16
434    16
621    17
619    17
761    17
375    17
904    17
646    17
582    17
257    17
       ..
90     60
308    60
931    60
752    60
469    60
464    60
234    60
694    60
934    61
351    61
106    61
520    62
266    62
858    63
777    63
364    63
845    64
423    64
318    65
651    65
564    65
211    66
349    68
573    68
559    69
585    69
767    70
803    70
860    70
481    73
Name: age, dtype: int64

## Excercise Two

using the drinks dataset again and refering to the code demonstrated above, write code to answer these questions:

In [86]:
# filter DataFrame to only include European countries
#drinks.head()
drinks[drinks.continent=='EU']

country  beer_servings  spirit_servings  wine_servings  \
1               Albania             89              132             54   
3               Andorra            245              138            312   
7               Armenia             21              179             11   
9               Austria            279               75            191   
10           Azerbaijan             21               46              5   
15              Belarus            142              373             42   
16              Belgium            295               84            212   
21   Bosnia-Herzegovina             76              173              8   
25             Bulgaria            231              252             94   
42              Croatia            230               87            254   
44               Cyprus            192              154            113   
45       Czech Republic            361              170            134   
48              Denmark            224               81            278   
57              Estonia            224              194             59   
60              Finland            263              133             97   
61               France            127              151            370   
64              Georgia             52              100            149   
65              Germany            346              117            175   
67               Greece            133              112            218   
75              Hungary            234              215            185   
76              Iceland            233               61             78   
81              Ireland            313              118            165   
83                Italy             85               42            237   
93               Latvia            281              216             62   
98            Lithuania            343              244             56   
99           Luxembourg            236              133            271   
105               Malta            149              100            120   
111              Monaco              0                0              0   
113          Montenegro             31              114            128   
120         Netherlands            251               88            190   
126              Norway            169               71            129   
135              Poland            343              215             56   
136            Portugal            194               67            339   
139             Moldova            109              226             18   
140             Romania            297              122            167   
147          San Marino              0                0              0   
151              Serbia            283              131            127   
155            Slovakia            196              293            116   
156            Slovenia            270               51            276   
160               Spain            284              157            112   
165              Sweden            152               60            186   
166         Switzerland            185              100            280   
170           Macedonia            106               27             86   
180             Ukraine            206              237             45   
182      United Kingdom            219              126            195   

     total_litres_of_pure_alcohol continent  
1                             4.9        EU  
3                            12.4        EU  
7                             3.8        EU  
9                             9.7        EU  
10                            1.3        EU  
15                           14.4        EU  
16                           10.5        EU  
21                            4.6        EU  
25                           10.3        EU  
42                           10.2        EU  
44                            8.2        EU  
45                           11.8        EU  
48           

In [89]:
# filter DataFrame to only include European countries with wine_servings > 300
drinks[(drinks.continent=='EU') & (drinks.wine_servings > 300)]

country  beer_servings  spirit_servings  wine_servings  \
3     Andorra            245              138            312   
61     France            127              151            370   
136  Portugal            194               67            339   

     total_litres_of_pure_alcohol continent  
3                            12.4        EU  
61                           11.8        EU  
136                          11.0        EU

In [102]:
# calculate the average 'beer_servings' for all of Europe
drinks[(drinks.continent=='EU')].beer_servings.mean()

193.77777777777777

In [109]:
# determine which 10 countries have the highest total_litres_of_pure_alcohol
drinks.sort_values(by='total_litres_of_pure_alcohol', ascending=False).head(10)

country  beer_servings  spirit_servings  wine_servings  \
15              Belarus            142              373             42   
98            Lithuania            343              244             56   
3               Andorra            245              138            312   
68              Grenada            199              438             28   
45       Czech Republic            361              170            134   
61               France            127              151            370   
141  Russian Federation            247              326             73   
81              Ireland            313              118            165   
155            Slovakia            196              293            116   
99           Luxembourg            236              133            271   

     total_litres_of_pure_alcohol continent  
15                           14.4        EU  
98                           12.9        EU  
3                            12.4        EU  
68                           11.9       NaN  
45                           11.8        EU  
61                           11.8        EU  
141                          11.5        AS  
81                           11.4        EU  
155                          11.4        EU  
99                           11.4        EU

# Optional Excercises

### Merging Data

In [113]:
#help(pd.merge)
# read 'u.item' into 'movies'
movie_cols = ['movie_id', 'title']
movies = pd.read_table('u.item', sep='|', header=None, names=movie_cols, usecols=[0, 1])


In [111]:
# read 'u.data' into 'ratings'
rating_cols = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_table('u.data', sep='\t', header=None, names=rating_cols)

In [114]:
# merge 'movies' and 'ratings' (inner join on 'movie_id')
movie_ratings = pd.merge(movies, ratings)
movies.shape
ratings.shape
movie_ratings.shape

(100000, 5)

### Grouping Data

In [115]:
movie_ratings.columns

Index([u'movie_id', u'title', u'user_id', u'rating', u'timestamp'], dtype='object')

In [116]:
movie_ratings[['title', 'rating']].groupby('title').sum()

rating
title                                                     
'Til There Was You (1997)                               21
1-900 (1994)                                            13
101 Dalmatians (1996)                                  317
12 Angry Men (1957)                                    543
187 (1997)                                             124
2 Days in the Valley (1996)                            300
20,000 Leagues Under the Sea (1954)                    252
2001: A Space Odyssey (1968)                          1028
3 Ninjas: High Noon At Mega Mountain (1998)              5
39 Steps, The (1935)                                   239
8 1/2 (1963)                                           145
8 Heads in a Duffel Bag (1997)                          13
8 Seconds (1994)                                        15
A Chef in Love (1996)                                   33
Above the Rim (1994)                                    15
Absolute Power (1997)                                  428
Abyss, The (1989)                                      542
Ace Ventura: Pet Detective (1994)                      314
Ace Ventura: When Nature Calls (1995)                   99
Across the Sea of Time (1995)                           11
Addams Family Values (1993)                            245
Addicted to Love (1997)                                171
Addiction, The (1995)                                   24
Adventures of Pinocchio, The (1996)                    119
Adventures of Priscilla, Queen of the Desert, T...     399
Adventures of Robin Hood, The (1938)                   254
Affair to Remember, An (1957)                          109
African Queen, The (1951)                              636
Afterglow (1997)                                        56
Age of Innocence, The (1993)                           220
...                                                    ...
Window to Paris (1994)                                   4
Wings of Courage (1995)                                  4
Wings of Desire (1987)                                 228
Wings of the Dove, The (1997)                          276
Winnie the Pooh and the Blustery Day (1968)            285
Winter Guest, The (1997)                                31
Wishmaster (1997)                                       66
With Honors (1994)                                     141
Withnail and I (1987)                                   42
Witness (1985)                                           4
Wizard of Oz, The (1939)                              1003
Wolf (1994)                                            181
Woman in Question, The (1950)                            1
Women, The (1939)                                       55
Wonderful, Horrible Life of Leni Riefenstahl, T...      40
Wonderland (1997)                                       32
Wooden Man's Bride, The (Wu Kui) (1994)                  8
World of Apu, The (Apur Sansar) (1959)                  24
Wrong Trousers, The (1993)                             527
Wyatt Earp (1994)                                      155
Yankee Zulu (1994)                                       1
Year of the Horse (1997)                                23
You So Crazy (1994)                                      3
Young Frankenstein (1974)                              789
Young Guns (1988)                                      324
Young Guns II (1990)                                   122
Young Poisoner's Handbook, The (1995)                  137
Zeus and Roxanne (1997)                                 13
unknown                                                 31
Á köldum klaka (Cold Fever) (1994)                       3

[1664 rows x 1 columns]

### Handling Missing Values

In [117]:
# missing values are usually excluded by default
#drinks.continent.value_counts()              # excludes missing values
drinks.continent.value_counts(dropna=False)  # includes missing values

AF     53
EU     45
AS     44
NaN    23
OC     16
SA     12
Name: continent, dtype: int64

In [120]:
# find missing values in a Series
#drinks.continent.isnull()           # True if missing, False if not missing
#drinks.continent.isnull().sum()     # count the missing values
#drinks.continent.notnull()          # True if not missing, False if missing
drinks[drinks.continent.isnull()]  # only show rows where continent is not missing

country  beer_servings  spirit_servings  \
5               Antigua & Barbuda            102              128   
11                        Bahamas            122              176   
14                       Barbados            143              173   
17                         Belize            263              114   
32                         Canada            240              122   
41                     Costa Rica            149               87   
43                           Cuba             93              137   
50                       Dominica             52              286   
51             Dominican Republic            193              147   
54                    El Salvador             52               69   
68                        Grenada            199              438   
69                      Guatemala             53               69   
73                          Haiti              1              326   
74                       Honduras             69               98   
84                        Jamaica             82               97   
109                        Mexico            238               68   
122                     Nicaragua             78              118   
130                        Panama            285              104   
143             St. Kitts & Nevis            194              205   
144                     St. Lucia            171              315   
145  St. Vincent & the Grenadines            120              221   
174             Trinidad & Tobago            197              156   
184                           USA            249              158   

     wine_servings  total_litres_of_pure_alcohol continent  
5               45                           4.9       NaN  
11              51                           6.3       NaN  
14              36                           6.3       NaN  
17               8                           6.8       NaN  
32             100                           8.2       NaN  
41              11                           4.4       NaN  
43               5                           4.2       NaN  
50              26                           6.6       NaN  
51               9                           6.2       NaN  
54               2                           2.2       NaN  
68              28                          11.9       NaN  
69               2                           2.2       NaN  
73               1                           5.9       NaN  
74               2                           3.0       NaN  
84               9                           3.4       NaN  
109              5                           5.5       NaN  
122              1                           3.5       NaN  
130             18                           7.2       NaN  
143             32                           7.7       NaN  
144             71                          10.1       NaN  
145             11                           6.3       NaN  
174              7                           6.4       NaN  
184             84                           8.7       NaN

In [121]:
# use 'tilde' ~ to negate the boolean values
~drinks.continent.isnull()  

0       True
1       True
2       True
3       True
4       True
5      False
6       True
7       True
8       True
9       True
10      True
11     False
12      True
13      True
14     False
15      True
16      True
17     False
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
       ...  
163     True
164     True
165     True
166     True
167     True
168     True
169     True
170     True
171     True
172     True
173     True
174    False
175     True
176     True
177     True
178     True
179     True
180     True
181     True
182     True
183     True
184    False
185     True
186     True
187     True
188     True
189     True
190     True
191     True
192     True
Name: continent, dtype: bool

In [ ]:
# side note: understanding axes
drinks.sum(axis=0)      # sums "down" the 0 axis (rows)
drinks.sum()            # axis=0 is the default
drinks.sum(axis=1)      # sums "across" the 1 axis (columns)

In [129]:
# find missing values in a DataFrame
drinks.isnull()             # DataFrame of booleans
drinks.isnull().sum()       # count the missing values in each column

country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
continent                       0
dtype: int64

In [128]:
# fill in missing values
#drinks.continent.fillna(value='NA')                 # fill in missing values with 'NA'
drinks.continent.fillna(value='NA', inplace=True)   # modifies 'drinks' in-place
drinks.head(100)

country  beer_servings  spirit_servings  wine_servings  \
0          Afghanistan              0                0              0   
1              Albania             89              132             54   
2              Algeria             25                0             14   
3              Andorra            245              138            312   
4               Angola            217               57             45   
5    Antigua & Barbuda            102              128             45   
6            Argentina            193               25            221   
7              Armenia             21              179             11   
8            Australia            261               72            212   
9              Austria            279               75            191   
10          Azerbaijan             21               46              5   
11             Bahamas            122              176             51   
12             Bahrain             42               63              7   
13          Bangladesh              0                0              0   
14            Barbados            143              173             36   
15             Belarus            142              373             42   
16             Belgium            295               84            212   
17              Belize            263              114              8   
18               Benin             34                4             13   
19              Bhutan             23                0              0   
20             Bolivia            167               41              8   
21  Bosnia-Herzegovina             76              173              8   
22            Botswana            173               35             35   
23              Brazil            245              145             16   
24              Brunei             31                2              1   
25            Bulgaria            231              252             94   
26        Burkina Faso             25                7              7   
27             Burundi             88                0              0   
28       Cote d'Ivoire             37                1              7   
29          Cabo Verde            144               56             16   
..                 ...            ...              ...            ...   
70              Guinea              9                0              2   
71       Guinea-Bissau             28               31             21   
72              Guyana             93              302              1   
73               Haiti              1              326              1   
74            Honduras             69               98              2   
75             Hungary            234              215            185   
76             Iceland            233               61             78   
77               India              9              114              0   
78           Indonesia              5                1              0   
79                Iran              0                0              0   
80                Iraq              9                3              0   
81             Ireland            313              118            165   
82              Israel             63               69              9   
83               Italy             85               42            237   
84             Jamaica             82               97              9   
85               Japan             77              202             16   
86              Jordan              6               21              1   
87          Kazakhstan            124              246             12   
88               Kenya             58               22              2   
89            Kiribati             21               34              1   
90              Kuwait              0                0              0   
91          Kyrgyzstan             31               97              6   
92                Laos             62                0            123   
