In [1]:
# Data Science Course Week 1 - Data Manipulation using Pandas

## Here we will be using real data sources to explore the features of Pandas


In [10]:
import pandas as pd

In [6]:
1==5

False

# Class Workshop

## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [9]:
import numpy as np

### Creating ndarrays
An array object represents a multidimensional, homogeneous array of fixed-size items.

In [12]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
a,b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [9]:
import numpy as np
?np.arange()

In [20]:
c = a-b
a,b,c

(array([20, 30, 40, 50]), array([0, 1, 2, 3]), array([20, 29, 38, 47]))

In [8]:
b**2

array([0, 1, 4, 9])

In [7]:
?np.random.randint()

In [21]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
help(np.random.randint)

Help on built-in function randint:

randint(...)
    randint(low, high=None, size=None)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution in the
    "half-open" interval [`low`, `high`). If `high` is None (the default),
    then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is the *highest* such
        integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    

In [10]:
a

array([ 0.,  0.,  0.])

In [11]:
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [12]:
c

array([[[1, 4, 2, 7],
        [3, 2, 8, 4],
        [4, 1, 9, 4]],

       [[8, 5, 7, 3],
        [7, 8, 3, 9],
        [7, 6, 2, 6]]])

## Indexing, Slicing and Iterating

In [22]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [24]:
a[2:5]

array([ 4,  9, 16])

In [25]:
a[0:3]

array([0, 1, 4])

In [26]:
a[1:3]

array([1, 4])

### Reading Files, Selecting Columns, and Summarizing

MovieLens 100k movie rating data:
    main page: http://grouplens.org/datasets/movielens/
    data dictionary: http://files.grouplens.org/datasets/movielens/ml-100k-README.txt
    files: u.user, u.data, u.item

In [27]:
# can read a file from local computer or directly from a URL
pd.read_table('u.user', header=None)

0
0         1|24|M|technician|85711
1              2|53|F|other|94043
2             3|23|M|writer|32067
3         4|24|M|technician|43537
4              5|33|F|other|15213
5          6|42|M|executive|98101
6      7|57|M|administrator|91344
7      8|36|M|administrator|05201
8            9|29|M|student|01002
9            10|53|M|lawyer|90703
10            11|39|F|other|30329
11            12|28|F|other|06405
12         13|47|M|educator|29206
13        14|45|M|scientist|55106
14         15|49|F|educator|97301
15    16|21|M|entertainment|10309
16       17|30|M|programmer|06355
17            18|35|F|other|37212
18        19|40|M|librarian|02138
19        20|42|F|homemaker|95660
20           21|26|M|writer|30068
21           22|25|M|writer|40206
22           23|30|F|artist|48197
23           24|21|F|artist|94533
24         25|39|M|engineer|55107
25         26|49|M|engineer|21044
26        27|40|F|librarian|30030
27           28|32|M|writer|55369
28       29|41|M|programmer|94043
29           30|7|M|student|55436
..                            ...
913          914|44|F|other|08105
914  915|50|M|entertainment|60614
915       916|27|M|engineer|N2L5N
916        917|22|F|student|20006
917      918|40|M|scientist|70116
918          919|25|M|other|14216
919         920|30|F|artist|90008
920        921|20|F|student|98801
921  922|29|F|administrator|21114
922        923|21|M|student|E2E3R
923          924|29|M|other|11753
924       925|18|F|salesman|49036
925  926|49|M|entertainment|01701
926     927|23|M|programmer|55428
927        928|21|M|student|55408
928      929|44|M|scientist|53711
929      930|28|F|scientist|07310
930       931|60|M|educator|33556
931       932|58|M|educator|06437
932        933|28|M|student|48105
933       934|61|M|engineer|22902
934         935|42|M|doctor|66221
935          936|24|M|other|32789
936       937|48|M|educator|98072
937     938|38|F|technician|55038
938        939|26|F|student|33319
939  940|32|M|administrator|02215
940        941|20|M|student|97229
941      942|48|F|librarian|78209
942        943|22|M|student|77841

[943 rows x 1 columns]

In [15]:
? pd.read_table

Now having seen the data, read it in again but now with the pipe separator/delimiter.

In [16]:
# read 'u.user' and asign to 'users' so that we can re-use the data
import pandas as pd
user_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_table('u.user', sep='|', header=None, names=user_cols, index_col='user_id', dtype={'zip_code':str})

Now try running the example code below, uncommenting each line one at a time to see what results

In [36]:
# examine the users data
#users                   # print the first 30 and last 30 rows
#type(users)             # DataFrame
#users.head()            # print the first 5 rows
#users.head(10)          # print the first 10 rows
#users.tail()            # print the last 5 rows
users.index             # "the index" (aka "the labels")
#users.columns           # column names (which is "an index")
#users.dtypes            # data types of each column
#users.shape             # number of rows and columns
#users.values            # underlying numpy array
#users.info()            # concise summary (including memory usage)

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
           dtype='int64', name='user_id', length=943)

Now try some of the different methods for selecting a column from a dataframe by name.

In [35]:
# select a column

#users['gender']         # select one column
type(users['gender'])   # Series
#users[['gender']]
#type(users[['gender']])   # DataFrame
#users.gender            # select one column using the DataFrame attribute
#type(users.occupation)

pandas.core.series.Series

Now try some built in pandas methods for producing summary descriptive information from a dataframe.

In [31]:
# summarize (describe) the data

#users.describe()                    # describe all numeric columns
#users.describe(include=['object'])  # describe all object columns (can include multiple types)
users.describe(include='all')       # describe all columns
#users.age.describe()             # describe a single column
#users.age.mean()                    # only calculate the mean


age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [45]:
# count the number of occurrences of each value
users.occupation.value_counts()     # most useful for categorical variables
#users.age.value_counts()        # can also be used with numeric variables

student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
salesman          12
lawyer            12
none               9
homemaker          7
doctor             7
Name: occupation, dtype: int64

# Student Exercises

## Excercise One

### Data

WHO alcohol consumption data:
    article: http://fivethirtyeight.com/datalab/dear-mona-followup-where-do-people-drink-the-most-beer-wine-and-spirits/    
    original data: https://github.com/fivethirtyeight/data/tree/master/alcohol-consumption
    file: drinks.csv (with additional 'continent' column)


In [38]:
# read drinks.csv into a DataFrame called 'drinks'
drinks = pd.read_table('drinks.csv', sep=',')
#drinks = pd.read_csv('drinks.csv')              # assumes separator is comma

In [40]:
# print the head and the tail
#drinks.head()
#drinks.tail()
drinks.describe()
#drinks.country.describe()

beer_servings  spirit_servings  wine_servings  \
count     193.000000       193.000000     193.000000   
mean      106.160622        80.994819      49.450777   
std       101.143103        88.284312      79.697598   
min         0.000000         0.000000       0.000000   
25%        20.000000         4.000000       1.000000   
50%        76.000000        56.000000       8.000000   
75%       188.000000       128.000000      59.000000   
max       376.000000       438.000000     370.000000   

       total_litres_of_pure_alcohol  
count                    193.000000  
mean                       4.717098  
std                        3.773298  
min                        0.000000  
25%                        1.300000  
50%                        4.200000  
75%                        7.200000  
max                       14.400000

In [41]:
# examine the default index, data types, and shape
drinks.index
#drinks.dtypes
#drinks.shape

RangeIndex(start=0, stop=193, step=1)

In [43]:
# print the 'beer_servings' Series
drinks[['beer_servings']]
#drinks.beer_servings


beer_servings
0                0
1               89
2               25
3              245
4              217
5              102
6              193
7               21
8              261
9              279
10              21
11             122
12              42
13               0
14             143
15             142
16             295
17             263
18              34
19              23
20             167
21              76
22             173
23             245
24              31
25             231
26              25
27              88
28              37
29             144
..             ...
163            128
164             90
165            152
166            185
167              5
168              2
169             99
170            106
171              1
172             36
173             36
174            197
175             51
176             51
177             19
178              6
179             45
180            206
181             16
182            219
183             36
184            249
185            115
186             25
187             21
188            333
189            111
190              6
191             32
192             64

[193 rows x 1 columns]

In [44]:
# calculate the average 'beer_servings' for the entire dataset
drinks.describe()                   # summarize all numeric columns
#drinks.beer_servings.describe()     # summarize only the 'beer_servings' Series
#drinks.beer_servings.mean()         # only calculate the mean


beer_servings  spirit_servings  wine_servings  \
count     193.000000       193.000000     193.000000   
mean      106.160622        80.994819      49.450777   
std       101.143103        88.284312      79.697598   
min         0.000000         0.000000       0.000000   
25%        20.000000         4.000000       1.000000   
50%        76.000000        56.000000       8.000000   
75%       188.000000       128.000000      59.000000   
max       376.000000       438.000000     370.000000   

       total_litres_of_pure_alcohol  
count                    193.000000  
mean                       4.717098  
std                        3.773298  
min                        0.000000  
25%                        1.300000  
50%                        4.200000  
75%                        7.200000  
max                       14.400000

In [47]:

# count the number of occurrences of each 'continent' value and see if it looks correct
#drinks.continent.value_counts()
#drinks.country.value_counts()

#### Filtering and Sorting

using users data set again

In [21]:
# logical filtering: only show users with age < 20
#young_bool = users.age < 20         # create a Series of booleans...
#users[young_bool]                   # ...and use that Series to filter rows
#users[users.age < 20]               # or, combine into a single step
users[users.age < 20].occupation    # select one column from the filtered results
#users[users.age < 20].occupation.value_counts()     # value_counts of resulting Series

user_id
30           student
36           student
52           student
57              none
67           student
68           student
101          student
110          student
142            other
179    entertainment
206          student
221          student
223          student
246          student
257          student
258          student
262          student
270          student
281          student
289             none
291          student
303          student
320          student
341          student
347          student
367          student
368          student
375    entertainment
393          student
397          student
           ...      
601           artist
609          student
618          student
619          student
620           writer
621          student
624          student
628             none
631          student
632          student
642          student
646          student
674          student
700          student
710          student
729          student
747  

In [22]:
# logical filtering with multiple conditions
#users[(users.age  >= 20) & (users.gender=='M')]       # ampersand for AND condition
#users[(users.age < 20) | (users.age > 60)]          # pipe for OR condition
users[users.occupation.isin(['doctor', 'lawyer'])]  # alternative to multiple OR conditions


age gender occupation zip_code
user_id                                
10        53      M     lawyer    90703
125       30      M     lawyer    22202
126       28      F     lawyer    20015
138       46      M     doctor    53211
161       50      M     lawyer    55104
205       47      M     lawyer    06371
251       28      M     doctor    85032
299       29      M     doctor    63108
339       35      M     lawyer    37901
365       29      M     lawyer    20009
419       37      M     lawyer    43215
427       51      M     doctor    85258
444       51      F     lawyer    53202
589       21      M     lawyer    90034
680       33      M     lawyer    90405
841       45      M     doctor    47401
845       64      M     doctor    97405
846       27      M     lawyer    47130
935       42      M     doctor    66221

In [23]:
# sorting
#users.age.sort_values()                   # sort a column
#users.sort_values(by='age')                   # sort a DataFrame by a single column
#users.sort_values(by='age', ascending=False)  # use descending order instead
users.sort_values(by=['occupation', 'age'])   # sort by multiple columns


age gender     occupation zip_code
user_id                                    
118       21      M  administrator    90210
180       22      F  administrator    60202
282       22      M  administrator    20057
317       22      M  administrator    13210
439       23      F  administrator    20817
509       23      M  administrator    10011
394       25      M  administrator    96819
665       25      M  administrator    55412
726       25      F  administrator    80538
78        26      M  administrator    61801
86        26      M  administrator    46005
62        27      F  administrator    97214
525       27      F  administrator    19711
261       28      M  administrator    85202
500       28      M  administrator    94305
748       28      M  administrator    94720
750       28      M  administrator    32303
768       29      M  administrator    12866
922       29      F  administrator    21114
42        30      M  administrator    17870
174       30      F  administrator    52302
190       30      M  administrator    95938
436       30      F  administrator    17345
447       30      M  administrator    55113
95        31      M  administrator    10707
578       31      M  administrator    M7A1A
762       32      M  administrator    95050
940       32      M  administrator    02215
191       33      M  administrator    95161
400       33      F  administrator    78213
...      ...    ...            ...      ...
668       29      F         writer    10016
199       30      M         writer    17604
557       30      F         writer    11217
28        32      M         writer    55369
122       32      F         writer    22206
796       32      F         writer    33755
833       34      M         writer    90019
264       36      F         writer    90064
385       36      M         writer    10003
911       37      F         writer    53210
504       40      F         writer    92115
798       40      F         writer    64131
842       40      M         writer    93055
390       42      F         writer    85016
745       42      M         writer    55113
491       43      F         writer    53711
236       44      F         writer    53214
389       44      F         writer    83702
736       48      F         writer    94618
829       48      M         writer    80209
196       49      M         writer    55105
518       49      F         writer    99709
853       49      M         writer    40515
503       50      F         writer    27514
772       50      M         writer    27105
548       51      M         writer    95468
370       52      M         writer    08534
392       52      M         writer    59801
558       56      F         writer    63132
464       60      M         writer    94583

[943 rows x 4 columns]

## Excercise Two

using the drinks dataset again and refering to the code demonstrated above, write code to answer these questions:

In [86]:
# filter DataFrame to only include European countries
#drinks.head()
drinks[drinks.continent=='EU']

country  beer_servings  spirit_servings  wine_servings  \
1               Albania             89              132             54   
3               Andorra            245              138            312   
7               Armenia             21              179             11   
9               Austria            279               75            191   
10           Azerbaijan             21               46              5   
15              Belarus            142              373             42   
16              Belgium            295               84            212   
21   Bosnia-Herzegovina             76              173              8   
25             Bulgaria            231              252             94   
42              Croatia            230               87            254   
44               Cyprus            192              154            113   
45       Czech Republic            361              170            134   
48              Denmark            224               81            278   
57              Estonia            224              194             59   
60              Finland            263              133             97   
61               France            127              151            370   
64              Georgia             52              100            149   
65              Germany            346              117            175   
67               Greece            133              112            218   
75              Hungary            234              215            185   
76              Iceland            233               61             78   
81              Ireland            313              118            165   
83                Italy             85               42            237   
93               Latvia            281              216             62   
98            Lithuania            343              244             56   
99           Luxembourg            236              133            271   
105               Malta            149              100            120   
111              Monaco              0                0              0   
113          Montenegro             31              114            128   
120         Netherlands            251               88            190   
126              Norway            169               71            129   
135              Poland            343              215             56   
136            Portugal            194               67            339   
139             Moldova            109              226             18   
140             Romania            297              122            167   
147          San Marino              0                0              0   
151              Serbia            283              131            127   
155            Slovakia            196              293            116   
156            Slovenia            270               51            276   
160               Spain            284              157            112   
165              Sweden            152               60            186   
166         Switzerland            185              100            280   
170           Macedonia            106               27             86   
180             Ukraine            206              237             45   
182      United Kingdom            219              126            195   

     total_litres_of_pure_alcohol continent  
1                             4.9        EU  
3                            12.4        EU  
7                             3.8        EU  
9                             9.7        EU  
10                            1.3        EU  
15                           14.4        EU  
16                           10.5        EU  
21                            4.6        EU  
25                           10.3        EU  
42                           10.2        EU  
44                            8.2        EU  
45                           11.8        EU  
48           

In [89]:
# filter DataFrame to only include European countries with wine_servings > 300
drinks[(drinks.continent=='EU') & (drinks.wine_servings > 300)]

country  beer_servings  spirit_servings  wine_servings  \
3     Andorra            245              138            312   
61     France            127              151            370   
136  Portugal            194               67            339   

     total_litres_of_pure_alcohol continent  
3                            12.4        EU  
61                           11.8        EU  
136                          11.0        EU

In [102]:
# calculate the average 'beer_servings' for all of Europe
drinks[(drinks.continent=='EU')].beer_servings.mean()

193.77777777777777

In [109]:
# determine which 10 countries have the highest total_litres_of_pure_alcohol
drinks.sort_values(by='total_litres_of_pure_alcohol', ascending=False).head(10)

country  beer_servings  spirit_servings  wine_servings  \
15              Belarus            142              373             42   
98            Lithuania            343              244             56   
3               Andorra            245              138            312   
68              Grenada            199              438             28   
45       Czech Republic            361              170            134   
61               France            127              151            370   
141  Russian Federation            247              326             73   
81              Ireland            313              118            165   
155            Slovakia            196              293            116   
99           Luxembourg            236              133            271   

     total_litres_of_pure_alcohol continent  
15                           14.4        EU  
98                           12.9        EU  
3                            12.4        EU  
68                           11.9       NaN  
45                           11.8        EU  
61                           11.8        EU  
141                          11.5        AS  
81                           11.4        EU  
155                          11.4        EU  
99                           11.4        EU

# Optional Excercises

### Merging Data

In [52]:
#help(pd.merge)
# read 'u.item' into 'movies'
movie_cols = ['movie_id', 'title']
movies = pd.read_table('u.item', sep='|', header=None, names=movie_cols, usecols=[0, 1])


In [53]:
# read 'u.data' into 'ratings'
rating_cols = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_table('u.data', sep='\t', header=None, names=rating_cols)

In [57]:
# merge 'movies' and 'ratings' (inner join on 'movie_id')
movie_ratings = pd.merge(movies, ratings)
#movies.shape
#ratings.shape
#movie_ratings.shape
movie_ratings.head()

movie_id             title  user_id  rating  timestamp
0         1  Toy Story (1995)      308       4  887736532
1         1  Toy Story (1995)      287       5  875334088
2         1  Toy Story (1995)      148       4  877019411
3         1  Toy Story (1995)      280       4  891700426
4         1  Toy Story (1995)       66       3  883601324

### Grouping Data

In [115]:
movie_ratings.columns

Index([u'movie_id', u'title', u'user_id', u'rating', u'timestamp'], dtype='object')

In [62]:
movie_ratings[['user_id', 'rating']].groupby('user_id').sum()

rating
user_id        
1           982
2           230
3           151
4           104
5           503
6           767
7          1598
8           224
9            94
10          774
11          627
12          224
13         1970
14          401
15          299
16          606
17           85
18         1075
19           71
20          149
21          478
22          429
23          549
24          294
25          316
26          315
27           81
28          294
29          124
30          162
...         ...
914          71
915          81
916        1067
917         124
918         345
919         753
920          84
921         360
922         428
923         307
924         308
925         100
926          66
927         443
928         150
929         181
930         187
931         227
932         956
933         487
934         644
935         153
936         532
937         135
938         353
939         209
940         370
941          89
942         337
943         573

[943 rows x 1 columns]

### Handling Missing Values

In [117]:
# missing values are usually excluded by default
#drinks.continent.value_counts()              # excludes missing values
drinks.continent.value_counts(dropna=False)  # includes missing values

AF     53
EU     45
AS     44
NaN    23
OC     16
SA     12
Name: continent, dtype: int64

In [24]:
# find missing values in a Series
#drinks.continent.isnull()           # True if missing, False if not missing
drinks.continent.isnull().sum()     # count the missing values
#drinks.continent.notnull()          # True if not missing, False if missing
#drinks[drinks.continent.isnull()]  # only show rows where continent is not missing

23

In [121]:
# use 'tilde' ~ to negate the boolean values
~drinks.continent.isnull()  

0       True
1       True
2       True
3       True
4       True
5      False
6       True
7       True
8       True
9       True
10      True
11     False
12      True
13      True
14     False
15      True
16      True
17     False
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
       ...  
163     True
164     True
165     True
166     True
167     True
168     True
169     True
170     True
171     True
172     True
173     True
174    False
175     True
176     True
177     True
178     True
179     True
180     True
181     True
182     True
183     True
184    False
185     True
186     True
187     True
188     True
189     True
190     True
191     True
192     True
Name: continent, dtype: bool

In [65]:
# side note: understanding axes
#drinks.sum(axis=0)      # sums "down" the 0 axis (rows)
#drinks.sum()            # axis=0 is the default
drinks.sum(axis=1)# sums "across" the 1 axis (columns)

0        0.0
1      279.9
2       39.7
3      707.4
4      324.9
5      279.9
6      447.3
7      214.8
8      555.4
9      554.7
10      73.3
11     355.3
12     114.0
13       0.0
14     358.3
15     571.4
16     601.5
17     391.8
18      52.1
19      23.4
20     219.8
21     261.6
22     248.4
23     413.2
24      34.6
25     587.3
26      43.3
27      94.3
28      49.0
29     220.0
       ...  
163    318.6
164     98.7
165    405.2
166    575.2
167     57.0
168     17.3
169    364.4
170    222.9
171      6.1
172     58.3
173     63.1
174    366.4
175     75.3
176     81.4
177    124.2
178     57.0
179     62.3
180    496.9
181    158.8
182    550.4
183     48.7
184    499.7
185    376.6
186    136.4
187     50.9
188    443.7
189    116.0
190      6.1
191     57.5
192     90.7
dtype: float64

In [29]:
# find missing values in a DataFrame
#drinks.isnull()             # DataFrame of booleans
drinks.isnull().sum()       # count the missing values in each column

country                          0
beer_servings                    0
spirit_servings                  0
wine_servings                    0
total_litres_of_pure_alcohol     0
continent                       23
dtype: int64

In [33]:
# fill in missing values
#drinks.continent.fillna(value='NA')                 # fill in missing values with 'NA'
#drinks.continent.fillna(value='NA', inplace=True)   # modifies 'drinks' in-place
#drinks.head(100)
drinks.isnull().sum()

country                         0
beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
continent                       0
dtype: int64